### ISSUE TITLE
Create Snapshot Space

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/governance#11]
It is fairly straightforward to do the basic level:

- create an ENS domain for OpenDataCommunity - 
- use this in creating the Snapshot space
- suggest we go ahead and set up one of the two sub domains:
    - Votes by Regen Rangers and ODC Jedi = based on one person / one vote or the presence of a ERC 721 in wallet
    
 docs are pretty clear:
 https://docs.snapshot.org/user-guides/spaces/create

**Comment by sarob** [comment]
How far along are on this? We have some proposals in discourse I’d like get agreement on.

**Comment by epowell101** [comment]
tabled for now, we are using the multisig
