### ISSUE TITLE
Publish draft pipeline documents on Discourse forum for broader comment & tracking

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/governance#5]
ASAP we should put our proposed first drafts of at least the following documents on our Forum:
- People Pipeline - to become an active community member
- People Pipeline - the ODC Jedi OATH
- People Pipeline - to achieve Regen Ranger designation
- People Pipeline - the Regen Ranger OATH
- Project Pipeline - sandbox ++ process

**Comment by sarob** [comment]
Out there on the forum. Next step merging.
